const randomProfile = require('random-profile-generator');

const profile = randomProfile.profile();
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Mentors', [
      {
        firstName: profile.firstName,
        lastName: profile.lastName,
        email: profile.email,
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 1300,
        password: 'password',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'JavaScript, React, Redux',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: 'https://kartinkin.net/uploads/posts/2022-02/1645236015_1-kartinkin-net-p-programmist-kartinki-1.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: profile.firstName,
        lastName: profile.lastName,
        email: profile.email,
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 2500,
        password: 'password',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'Python, MongoDB, Django',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: 'https://kartinkin.net/uploads/posts/2022-02/1645236015_1-kartinkin-net-p-programmist-kartinki-1.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: profile.firstName,
        lastName: profile.lastName,
        email: profile.email,
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 3400,
        password: 'password',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'Typescript, Redux, Redux-Saga, React, Redux-Thunk',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: 'https://www.osp.ru/FileStorage/DOCUMENTS_ILLUSTRATIONS/13237083/original.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: profile.firstName,
        lastName: profile.lastName,
        email: profile.email,
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 2450,
        password: 'password',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'Java, C++, C#',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: 'https://sevkor.ru/wp-content/uploads/2019/09/Sergej-Kachan-krasivyj.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: profile.firstName,
        lastName: profile.lastName,
        email: profile.email,
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 4500,
        password: 'password',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'React, Typescript, Redux, GraphQL',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: 'https://proforientator.ru/upload/iblock/58a/58a50c700a989f6ea574a0f987d20847.jpg',
        createdAt: new Date(),
        updatedAt: new Date(),
      }], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
