const randomProfile = require('random-profile-generator');

const profile = randomProfile.profile();
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Mentors', [
      {
        firstName: 'Robert',
        lastName: 'Castenlos',
        email: '1@1',
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 1300,
        password: '123',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'JavaScript, React, Redux',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: 'Oleg',
        lastName: 'BrainDit',
        email: '2@2',
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 2500,
        password: '123',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'Python, MongoDB, Django',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: 'Geek',
        lastName: 'More',
        email: '3@3',
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 3400,
        password: '123',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'Typescript, Redux, Redux-Saga, React, Redux-Thunk',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: 'Moreo',
        lastName: 'Caballera',
        email: '4@4',
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 2450,
        password: '123',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'Java, C++, C#',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        firstName: 'Jonathan',
        lastName: 'White',
        email: '5@5',
        zoom: profile.twitter,
        phone: profile.phone,
        video: 'on',
        call: 'on',
        chat: 'on',
        price: 4500,
        password: '123',
        education: 'MGU',
        job: 'mentor',
        profArea: 'IT',
        profScill: 'React, Typescript, Redux, GraphQL',
        aboutMe: profile.address,
        portfolio: 'portfolio',
        photo: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      }], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
